site_name: GrowNode Documentation
repo_url: https://github.com/ogghst/GrowNode
site_description: GrowNode is a vertical framework to build IoT devices targeted to growing plants in a controlled environment
site_author: Nicola Muratori - nicola.muratori@gmail.com
copyright: Copyright 2022 - Nicola Muratori 
theme:
  name: material
  include_sidebar: true
  features:
    - navigation.instant  
    - navigation.tabs    
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
  logo: img/grownode_logo_24.png
  favicon: img/grownode_logo_24.png
nav:
  - Introduction: 'index.md'
  - Platform: 'platform.md'
  - Install: 'start.md'
  - Play: 'workflow.md'
  - Ready Made Boards: 
     - 'boards/index.md'
     - EasyPot1: 'boards/boards_easypot1.md'
     - HydroBoard1: 'boards/boards_hb1.md'
     - HydroBoard2: 'boards/boards_hb2.md'
  - Reference Guide: 
     - 'reference/index.md'
     - 'reference/node.md'
     - 'reference/leaves.md'
     - 'reference/parameters.md'
     - Standard Leaves: 
        - 'reference/leaves_list/index.md'
        - 'reference/leaves_list/bme280.md'
        - 'reference/leaves_list/ina219.md'
     - 'reference/boards.md'
     - 'reference/events.md'
     - 'reference/networking.md'
     - 'reference/mqtt.md'
     - 'reference/power_management.md'
     - 'reference/display.md'
     - 'reference/logging.md'
     - 'reference/error.md'
     - 'reference/build_system.md'
  - Tutorials: 
     - 'tutorials/index.md'
     - 'tutorials/windows10_11_easy.md'
     - 'tutorials/ubuntu1804_2004_easy.md'
     - 'tutorials/ubuntu1804_2004_advanced.md'
     - 'tutorials/openhab_ubuntu1804_2004_easy.md'
  - Story: 'story.md'
  - API: 'html/index.html'
plugins:
    - search
