.TH "array_zip_iter_s" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
array_zip_iter_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCC_Array\fP * \fBar1\fP"
.br
.ti -1c
.RI "\fBCC_Array\fP * \fBar2\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "bool \fBlast_removed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Array zip iterator structure\&. Used to iterate over the elements of two arrays in lockstep in an ascending order until one of the Arrays is exhausted\&. The iterator also supports operations for safely adding and removing elements during iteration\&. 
.SH "Field Documentation"
.PP 
.SS "\fBCC_Array\fP* array_zip_iter_s::ar1"

.SS "\fBCC_Array\fP* array_zip_iter_s::ar2"

.SS "size_t array_zip_iter_s::index"

.SS "bool array_zip_iter_s::last_removed"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
