.TH "cc_array_iter_s" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cc_array_iter_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCC_Array\fP * \fBar\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "bool \fBlast_removed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Array iterator structure\&. Used to iterate over the elements of the array in an ascending order\&. The iterator also supports operations for safely adding and removing elements during iteration\&. 
.SH "Field Documentation"
.PP 
.SS "\fBCC_Array\fP* cc_array_iter_s::ar"
The array associated with this iterator 
.SS "size_t cc_array_iter_s::index"
The current position of the iterator\&. 
.SS "bool cc_array_iter_s::last_removed"
Set to true if the last returned element was removed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
