.TH "components/grownode/cc_common.c" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/cc_common.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcc_common_cmp_str\fP (const void *str1, const void *str2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int cc_common_cmp_str (const void * str1, const void * str2)"
String comparator function\&.
.PP
\fBParameters\fP
.RS 4
\fIstr1\fP first string 
.br
\fIstr2\fP second string
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
