.TH "cc_hashtable_s" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cc_hashtable_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBthreshold\fP"
.br
.ti -1c
.RI "uint32_t \fBhash_seed\fP"
.br
.ti -1c
.RI "int \fBkey_len\fP"
.br
.ti -1c
.RI "float \fBload_factor\fP"
.br
.ti -1c
.RI "\fBTableEntry\fP ** \fBbuckets\fP"
.br
.ti -1c
.RI "size_t(* \fBhash\fP )(const void *key, int l, uint32_t seed)"
.br
.ti -1c
.RI "int(* \fBkey_cmp\fP )(const void *k1, const void *k2)"
.br
.ti -1c
.RI "void *(* \fBmem_alloc\fP )(size_t \fBsize\fP)"
.br
.ti -1c
.RI "void *(* \fBmem_calloc\fP )(size_t blocks, size_t \fBsize\fP)"
.br
.ti -1c
.RI "void(* \fBmem_free\fP )(void *block)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBTableEntry\fP** cc_hashtable_s::buckets"

.SS "size_t cc_hashtable_s::capacity"

.SS "size_t(* cc_hashtable_s::hash) (const void *key, int l, uint32_t seed)"

.SS "uint32_t cc_hashtable_s::hash_seed"

.SS "int(* cc_hashtable_s::key_cmp) (const void *k1, const void *k2)"

.SS "int cc_hashtable_s::key_len"

.SS "float cc_hashtable_s::load_factor"

.SS "void*(* cc_hashtable_s::mem_alloc) (size_t \fBsize\fP)"

.SS "void*(* cc_hashtable_s::mem_calloc) (size_t blocks, size_t \fBsize\fP)"

.SS "void(* cc_hashtable_s::mem_free) (void *block)"

.SS "size_t cc_hashtable_s::size"

.SS "size_t cc_hashtable_s::threshold"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
