.TH "components/grownode/leaves/gn_bme280.c" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_bme280.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_bme280_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_bme280'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbme280_sensor_collect\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "void \fBgn_bme280_task\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_bme280_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TAG   'gn_leaf_bme280'"

.SH "Function Documentation"
.PP 
.SS "void bme280_sensor_collect (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "\fBgn_leaf_descriptor_handle_t\fP gn_bme280_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_bme280_task (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
