.TH "gn_bme280_data_t" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_bme280_data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bmp280_params_t \fBparams\fP"
.br
.ti -1c
.RI "bmp280_t \fBdev\fP"
.br
.ti -1c
.RI "esp_timer_handle_t \fBbme280_sensor_timer\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBsda_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBscl_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBupdate_time_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBactive_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBtemp_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBpress_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBhum_param\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::active_param"

.SS "esp_timer_handle_t gn_bme280_data_t::bme280_sensor_timer"

.SS "bmp280_t gn_bme280_data_t::dev"

.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::hum_param"

.SS "bmp280_params_t gn_bme280_data_t::params"

.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::press_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::scl_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::sda_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::temp_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_bme280_data_t::update_time_param"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
