.TH "components/grownode/leaves/gn_bme280.h" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_bme280.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_bme280_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBGN_LEAF_BME280_TYPE\fP [] = 'bme280'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_ACTIVE\fP [] = 'active'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_SDA\fP [] = 'SDA'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_SCL\fP [] = 'SCL'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_UPDATE_TIME_SEC\fP [] = 'upd_time_sec'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_TEMP\fP [] = 'temp'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_HUM\fP [] = 'hum'"
.br
.ti -1c
.RI "static const char \fBGN_BME280_PARAM_PRESS\fP [] = 'press'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_bme280_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const char GN_BME280_PARAM_ACTIVE[] = 'active'\fC [static]\fP"
whether the sensor is running 
.SS "const char GN_BME280_PARAM_HUM[] = 'hum'\fC [static]\fP"
humidity recorded 
.SS "const char GN_BME280_PARAM_PRESS[] = 'press'\fC [static]\fP"
pressure recorded 
.SS "const char GN_BME280_PARAM_SCL[] = 'SCL'\fC [static]\fP"
gpio number for I2C master data 
.SS "const char GN_BME280_PARAM_SDA[] = 'SDA'\fC [static]\fP"
gpio number for I2C master clock 
.SS "const char GN_BME280_PARAM_TEMP[] = 'temp'\fC [static]\fP"
temperature recorded 
.SS "const char GN_BME280_PARAM_UPDATE_TIME_SEC[] = 'upd_time_sec'\fC [static]\fP"
seconds between sensor sampling 
.SS "const char GN_LEAF_BME280_TYPE[] = 'bme280'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
