.TH "gn_cms_data_t" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_cms_data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBactive_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBadc_channel_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBmax_level_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBmin_level_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBact_level_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBtrg_hig_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBtrg_low_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBupd_time_sec_param\fP"
.br
.ti -1c
.RI "esp_adc_cal_characteristics_t * \fBadc_chars\fP"
.br
.ti -1c
.RI "esp_timer_handle_t \fBsensor_timer\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::act_level_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::active_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::adc_channel_param"

.SS "esp_adc_cal_characteristics_t* gn_cms_data_t::adc_chars"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::max_level_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::min_level_param"

.SS "esp_timer_handle_t gn_cms_data_t::sensor_timer"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::trg_hig_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::trg_low_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_cms_data_t::upd_time_sec_param"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
