.TH "components/grownode/leaves/gn_capacitive_moisture_sensor.h" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_capacitive_moisture_sensor.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_capacitive_moisture_sensor_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_capacitive_moisture_sensor_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
