.TH "components/grownode/leaves/gn_capacitive_moisture_sensor.c" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_capacitive_moisture_sensor.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_cms_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_cms'"
.br
.ti -1c
.RI "#define \fBDEFAULT_VREF\fP   1100"
.br
.ti -1c
.RI "#define \fBNO_OF_SAMPLES\fP   64"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_cms_task\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "void \fBgn_cms_sensor_collect\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_capacitive_moisture_sensor_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const adc_atten_t \fBatten\fP = ADC_ATTEN_DB_11"
.br
.ti -1c
.RI "static const adc_unit_t \fBunit\fP = ADC_UNIT_1"
.br
.ti -1c
.RI "static const adc_bits_width_t \fBwidth\fP = ADC_WIDTH_BIT_12"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_VREF   1100"

.SS "#define NO_OF_SAMPLES   64"

.SS "#define TAG   'gn_leaf_cms'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_capacitive_moisture_sensor_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SS "void gn_cms_sensor_collect (\fBgn_leaf_handle_t\fP leaf_config)"

.SS "void gn_cms_task (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const adc_atten_t atten = ADC_ATTEN_DB_11\fC [static]\fP"

.SS "const adc_unit_t unit = ADC_UNIT_1\fC [static]\fP"

.SS "const adc_bits_width_t width = ADC_WIDTH_BIT_12\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
