.TH "components/grownode/leaves/gn_capacitive_water_level.c" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_capacitive_water_level.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_cwl_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_cwl'"
.br
.ti -1c
.RI "#define \fBGN_CWL_TOUCH_THRESH\fP   (0)"
.br
.ti -1c
.RI "#define \fBGN_CWL_TOUCHPAD_FILTER_TOUCH_PERIOD\fP   (10)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_capacitive_water_level_task\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "void \fBgn_cwl_sensor_collect\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_capacitive_water_level_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GN_CWL_TOUCH_THRESH   (0)"

.SS "#define GN_CWL_TOUCHPAD_FILTER_TOUCH_PERIOD   (10)"

.SS "#define TAG   'gn_leaf_cwl'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_capacitive_water_level_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_capacitive_water_level_task (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_cwl_sensor_collect (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
