.TH "components/grownode/leaves/gn_ds18b20.h" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_ds18b20.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGN_DS18B20_MAX_SENSORS\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_ds18b20_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GN_DS18B20_MAX_SENSORS   4"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_ds18b20_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
