.TH "components/grownode/leaves/gn_ds18b20.c" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_ds18b20.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_ds18b20_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_ds18b20'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_ds18b20_task\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "void \fB_scan_sensors\fP (int gpio, size_t *sensor_count, ds18x20_addr_t *addrs)"
.br
.ti -1c
.RI "\fBgn_leaf_param_validator_result_t\fP \fB_gn_upd_time_sec_validator\fP (\fBgn_leaf_param_handle_t\fP param, void **param_value)"
.br
.ti -1c
.RI "void \fBgn_ds18b20_temp_sensor_collect\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_ds18b20_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const size_t \fBGN_DS18B20_STATE_STOP\fP = 0"
.br
.ti -1c
.RI "const size_t \fBGN_DS18B20_STATE_RUNNING\fP = 1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TAG   'gn_leaf_ds18b20'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_param_validator_result_t\fP _gn_upd_time_sec_validator (\fBgn_leaf_param_handle_t\fP param, void ** param_value)"

.SS "void _scan_sensors (int gpio, size_t * sensor_count, ds18x20_addr_t * addrs)"

.SS "\fBgn_leaf_descriptor_handle_t\fP gn_ds18b20_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_ds18b20_task (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_ds18b20_temp_sensor_collect (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const size_t GN_DS18B20_STATE_RUNNING = 1"

.SS "const size_t GN_DS18B20_STATE_STOP = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
