.TH "components/grownode/leaves/gn_ds18b20.h" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_ds18b20.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGN_DS18B20_MAX_SENSORS\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_ds18b20_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBGN_LEAF_DS18B20_TYPE\fP [] = 'ds18b20'"
.br
.ti -1c
.RI "static const int32_t \fBMIN_UPDATE_TIME_SEC\fP = 3"
.br
.ti -1c
.RI "static const int32_t \fBMAX_UPDATE_TIME_SEC\fP = 3600"
.br
.ti -1c
.RI "static const char \fBGN_DS18B20_PARAM_ACTIVE\fP [] = 'active'"
.br
.ti -1c
.RI "static const char \fBGN_DS18B20_PARAM_UPDATE_TIME_SEC\fP [16] = 'upd_time_sec'"
.br
.ti -1c
.RI "static const char \fBGN_DS18B20_PARAM_GPIO\fP [5] = 'gpio'"
.br
.ti -1c
.RI "static const char \fBGN_DS18B20_PARAM_SENSOR_NAMES\fP [\fBGN_DS18B20_MAX_SENSORS\fP][6]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GN_DS18B20_MAX_SENSORS   4"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_ds18b20_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const char GN_DS18B20_PARAM_ACTIVE[] = 'active'\fC [static]\fP"
whether the sensor is running 
.SS "const char GN_DS18B20_PARAM_GPIO[5] = 'gpio'\fC [static]\fP"
GPIO connected to the temp sensor 
.SS "const char GN_DS18B20_PARAM_SENSOR_NAMES[\fBGN_DS18B20_MAX_SENSORS\fP][6]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= { "temp1", "temp2",
        "temp3", "temp4" }
.fi
.SS "const char GN_DS18B20_PARAM_UPDATE_TIME_SEC[16] = 'upd_time_sec'\fC [static]\fP"
seconds between sensor sampling 
.SS "const char GN_LEAF_DS18B20_TYPE[] = 'ds18b20'\fC [static]\fP"

.SS "const int32_t MAX_UPDATE_TIME_SEC = 3600\fC [static]\fP"

.SS "const int32_t MIN_UPDATE_TIME_SEC = 3\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
