.TH "components/grownode/boards/gn_easypot1.c" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/boards/gn_easypot1.c
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_easypot1'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmoisture_callback\fP (const \fBgn_leaf_handle_t\fP \fBmoist\fP)"
.br
.ti -1c
.RI "void \fBtemp_callback\fP (const \fBgn_leaf_handle_t\fP \fBtemp\fP)"
.br
.ti -1c
.RI "void \fBgn_configure_easypot1\fP (\fBgn_node_handle_t\fP node)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBmoist\fP"
.br
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBtemp\fP"
.br
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBled_moist\fP"
.br
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBled_temp\fP"
.br
.ti -1c
.RI "double \fBmoist_last\fP"
.br
.ti -1c
.RI "double \fBtemp_last\fP"
.br
.ti -1c
.RI "const double \fBmoist_min\fP = 1"
.br
.ti -1c
.RI "const double \fBmoist_max\fP = 3"
.br
.ti -1c
.RI "const double \fBtemp_min\fP = 15"
.br
.ti -1c
.RI "const double \fBtemp_max\fP = 28"
.br
.ti -1c
.RI "const double \fBblink_time_high\fP = 300"
.br
.ti -1c
.RI "const double \fBblink_time_low\fP = 2000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TAG   'gn_easypot1'"

.SH "Function Documentation"
.PP 
.SS "void gn_configure_easypot1 (\fBgn_node_handle_t\fP node)"

.SS "void moisture_callback (const \fBgn_leaf_handle_t\fP moist)"

.SS "void temp_callback (const \fBgn_leaf_handle_t\fP temp)"

.SH "Variable Documentation"
.PP 
.SS "const double blink_time_high = 300"

.SS "const double blink_time_low = 2000"

.SS "\fBgn_leaf_handle_t\fP led_moist"

.SS "\fBgn_leaf_handle_t\fP led_temp"

.SS "\fBgn_leaf_handle_t\fP moist"

.SS "double moist_last"

.SS "const double moist_max = 3"

.SS "const double moist_min = 1"

.SS "\fBgn_leaf_handle_t\fP temp"

.SS "double temp_last"

.SS "const double temp_max = 28"

.SS "const double temp_min = 15"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
