.TH "components/grownode/boards/gn_easypot1.h" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/boards/gn_easypot1.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_configure_easypot1\fP (\fBgn_node_handle_t\fP node)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gn_configure_easypot1 (\fBgn_node_handle_t\fP node)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
