.TH "gn_gpio_data_t" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_gpio_data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_gpio_status_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_gpio_inverted_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_gpio_gpio_param\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_param_handle_t\fP gn_gpio_data_t::gn_gpio_gpio_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_gpio_data_t::gn_gpio_inverted_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_gpio_data_t::gn_gpio_status_param"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
