.TH "components/grownode/leaves/gn_hydroboard2_watering_control.h" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_hydroboard2_watering_control.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_hb2_watering_control_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_MIN_WATERING_INTERVAL\fP = 10"
.br
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_MAX_WATERING_INTERVAL\fP = 60*60*24*30"
.br
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_MIN_WATERING_TIME\fP = 1"
.br
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_MAX_WATERING_TIME\fP = 60*60"
.br
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_MIN_WATERING_TARGET_TEMP\fP = 12"
.br
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_MAX_WATERING_TARGET_TEMP\fP = 30"
.br
.ti -1c
.RI "static const int64_t \fBGN_HYDROBOARD2_MAX_HCC_CYCLE_TIME_SEC\fP = 60 * 5"
.br
.ti -1c
.RI "static const char \fBGN_LEAF_HYDROBOARD2_WATERING_CONTROL_TYPE\fP [] = 'watering_control'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_FAN\fP [] = 'leaf_PLT_FAN'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_PUMP\fP [] = 'leaf_PLT_PUMP'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_WAT_PUMP\fP [] = 'leaf_WAT_PUMP'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_COOL\fP [] = 'leaf_PLT_COOL'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_HOT\fP [] = 'leaf_PLT_HOT'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_ENV_FAN\fP [] = 'leaf_ENV_FAN'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_BME280\fP [] = 'leaf_BME280'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_DS18B20\fP [] = 'leaf_DS18B20'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_WAT_LEV\fP [] = 'leaf_WAT_LEV'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_LIGHT_1\fP [] = 'leaf_LIGHT_1'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_LIGHT_2\fP [] = 'leaf_LIGHT_2'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_WATERING_INTERVAL_SEC\fP [] = 'wat_int_sec'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_WATERING_TIME_SEC\fP [] = 'wat_time_sec'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_WATERING_TARGET_TEMP\fP [] = 'wat_t_temp'"
.br
.ti -1c
.RI "static const char \fBGN_HYDROBOARD2_WAT_CTR_PARAM_ACTIVE\fP [] = 'active'"
.br
.ti -1c
.RI "static const int32_t \fBGN_HYDROBOARD2_WAT_CTR_CYCLE_TIME_MS\fP = 1000L"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_hb2_watering_control_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const int64_t GN_HYDROBOARD2_MAX_HCC_CYCLE_TIME_SEC = 60 * 5\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_MAX_WATERING_INTERVAL = 60*60*24*30\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_MAX_WATERING_TARGET_TEMP = 30\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_MAX_WATERING_TIME = 60*60\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_MIN_WATERING_INTERVAL = 10\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_MIN_WATERING_TARGET_TEMP = 12\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_MIN_WATERING_TIME = 1\fC [static]\fP"

.SS "const int32_t GN_HYDROBOARD2_WAT_CTR_CYCLE_TIME_MS = 1000L\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_ACTIVE[] = 'active'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_BME280[] = 'leaf_BME280'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_DS18B20[] = 'leaf_DS18B20'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_ENV_FAN[] = 'leaf_ENV_FAN'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_LIGHT_1[] = 'leaf_LIGHT_1'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_LIGHT_2[] = 'leaf_LIGHT_2'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_COOL[] = 'leaf_PLT_COOL'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_FAN[] = 'leaf_PLT_FAN'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_HOT[] = 'leaf_PLT_HOT'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_PLT_PUMP[] = 'leaf_PLT_PUMP'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_WAT_LEV[] = 'leaf_WAT_LEV'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_LEAF_WAT_PUMP[] = 'leaf_WAT_PUMP'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_WATERING_INTERVAL_SEC[] = 'wat_int_sec'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_WATERING_TARGET_TEMP[] = 'wat_t_temp'\fC [static]\fP"

.SS "const char GN_HYDROBOARD2_WAT_CTR_PARAM_WATERING_TIME_SEC[] = 'wat_time_sec'\fC [static]\fP"

.SS "const char GN_LEAF_HYDROBOARD2_WATERING_CONTROL_TYPE[] = 'watering_control'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
