.TH "components/grownode/boards/gn_hydroboard2.h" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/boards/gn_hydroboard2.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_configure_hydroboard2\fP (\fBgn_node_config_handle_t\fP node)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gn_configure_hydroboard2 (\fBgn_node_config_handle_t\fP node)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
