.TH "gn_leaf_param" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_leaf_param
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_visibility_t\fP \fBaccess\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_storage_t\fP \fBstorage\fP"
.br
.ti -1c
.RI "\fBgn_param_val_handle_t\fP \fBparam_val\fP"
.br
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBleaf_config\fP"
.br
.ti -1c
.RI "\fBgn_validator_t\fP \fBvalidator\fP"
.br
.ti -1c
.RI "struct \fBgn_leaf_param\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_param_visibility_t\fP gn_leaf_param::access"

.SS "\fBgn_leaf_handle_t\fP gn_leaf_param::leaf_config"

.SS "char* gn_leaf_param::name"

.SS "struct \fBgn_leaf_param\fP* gn_leaf_param::next"

.SS "\fBgn_param_val_handle_t\fP gn_leaf_param::param_val"

.SS "\fBgn_leaf_param_storage_t\fP gn_leaf_param::storage"

.SS "\fBgn_validator_t\fP gn_leaf_param::validator"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
