.TH "gn_leaf_descriptor_t" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_leaf_descriptor_t \- this represents the description and status informations of the leaf  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtype\fP [\fBGN_LEAF_DESC_TYPE_SIZE\fP]"
.br
.ti -1c
.RI "\fBgn_leaf_task_callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "\fBgn_leaf_status_t\fP \fBstatus\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
this represents the description and status informations of the leaf 
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_task_callback\fP gn_leaf_descriptor_t::callback"

.SS "void* gn_leaf_descriptor_t::data"

.SS "\fBgn_leaf_status_t\fP gn_leaf_descriptor_t::status"

.SS "char gn_leaf_descriptor_t::type[\fBGN_LEAF_DESC_TYPE_SIZE\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
