.TH "gn_led_data_t" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_led_data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_led_status_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_led_inverted_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_led_blinktime_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_led_gpio_param\fP"
.br
.ti -1c
.RI "bool \fBblink_status\fP"
.br
.ti -1c
.RI "int \fBgpio\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool gn_led_data_t::blink_status"

.SS "\fBgn_leaf_param_handle_t\fP gn_led_data_t::gn_led_blinktime_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_led_data_t::gn_led_gpio_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_led_data_t::gn_led_inverted_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_led_data_t::gn_led_status_param"

.SS "int gn_led_data_t::gpio"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
