.TH "components/grownode/gn_leaf_context.h" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/gn_leaf_context.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBgn_leaf_context_handle_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_context_handle_t\fP \fBgn_leaf_context_create\fP ()"
.br
.ti -1c
.RI "size_t \fBgn_leaf_context_size\fP (\fBgn_leaf_context_handle_t\fP context)"
.br
.ti -1c
.RI "void \fBgn_leaf_context_destroy\fP (\fBgn_leaf_context_handle_t\fP context)"
.br
.ti -1c
.RI "void \fBgn_leaf_context_print\fP (\fBgn_leaf_context_handle_t\fP context)"
.br
.ti -1c
.RI "char * \fBgn_leaf_context_get_key_at\fP (\fBgn_leaf_context_handle_t\fP context, size_t index)"
.br
.ti -1c
.RI "void * \fBgn_leaf_context_set\fP (\fBgn_leaf_context_handle_t\fP context, char *key, void *value)"
.br
.ti -1c
.RI "void * \fBgn_leaf_context_delete\fP (\fBgn_leaf_context_handle_t\fP context, char *key)"
.br
.ti -1c
.RI "void * \fBgn_leaf_context_get\fP (\fBgn_leaf_context_handle_t\fP context, char *key)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBgn_leaf_context_handle_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_context_handle_t\fP gn_leaf_context_create ()"

.SS "void* gn_leaf_context_delete (\fBgn_leaf_context_handle_t\fP context, char * key)"

.SS "void gn_leaf_context_destroy (\fBgn_leaf_context_handle_t\fP context)"

.SS "void* gn_leaf_context_get (\fBgn_leaf_context_handle_t\fP context, char * key)"

.SS "char* gn_leaf_context_get_key_at (\fBgn_leaf_context_handle_t\fP context, size_t index)"

.SS "void gn_leaf_context_print (\fBgn_leaf_context_handle_t\fP context)"

.SS "void* gn_leaf_context_set (\fBgn_leaf_context_handle_t\fP context, char * key, void * value)"

.SS "size_t gn_leaf_context_size (\fBgn_leaf_context_handle_t\fP context)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
