.TH "gn_mqtt_node_config_message_t" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_mqtt_node_config_message_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_node_config_handle_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "char \fBtopic\fP [\fB_GN_MQTT_MAX_TOPIC_LENGTH\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_node_config_handle_t\fP gn_mqtt_node_config_message_t::config"

.SS "char gn_mqtt_node_config_message_t::topic[\fB_GN_MQTT_MAX_TOPIC_LENGTH\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
