.TH "components/grownode/gn_mqtt_protocol.h" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/gn_mqtt_protocol.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_GN_MQTT_MAX_TOPIC_LENGTH\fP   80"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_MAX_PAYLOAD_LENGTH\fP   CONFIG_GROWNODE_MQTT_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_COMMAND_MESS\fP   'cmd'"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_STATUS_MESS\fP   'sts'"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_LOG_MESS\fP   'log'"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_PAYLOAD_RST\fP   'RST'"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_PAYLOAD_OTA\fP   'OTA'"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_PAYLOAD_RBT\fP   'RBT'"
.br
.ti -1c
.RI "#define \fB_GN_MQTT_DEFAULT_QOS\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_publish_leaf\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.RI "subscribe leaf to the MQTT server in order to receive messages "
.ti -1c
.RI "esp_err_t \fBgn_mqtt_subscribe_leaf_param\fP (\fBgn_leaf_param_handle_t\fP param)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_init\fP (\fBgn_config_handle_t\fP \fBconfig\fP)"
.br
.RI "inits the MQTT subsystem "
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_node_config\fP (\fBgn_node_handle_t\fP conf)"
.br
.RI "send node parameters via JSON message to the server "
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_leaf_message\fP (\fBgn_leaf_handle_t\fP leaf, const char *msg)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_leaf_param\fP (\fBgn_leaf_param_handle_t\fP \fBconfig\fP)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_startup_message\fP (\fBgn_config_handle_t\fP _config)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_reboot_message\fP (\fBgn_config_handle_t\fP _config)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_reset_message\fP (\fBgn_config_handle_t\fP _config)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_ota_message\fP (\fBgn_config_handle_t\fP _config)"
.br
.ti -1c
.RI "\fBgn_err_t\fP \fBgn_mqtt_send_log_message\fP (\fBgn_config_handle_t\fP _config, char *log_tag, \fBgn_log_level_t\fP level, char *message)"
.br
.RI "sends log message via MQTT "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _GN_MQTT_COMMAND_MESS   'cmd'"

.SS "#define _GN_MQTT_DEFAULT_QOS   0"

.SS "#define _GN_MQTT_LOG_MESS   'log'"

.SS "#define _GN_MQTT_MAX_PAYLOAD_LENGTH   CONFIG_GROWNODE_MQTT_BUFFER_SIZE"

.SS "#define _GN_MQTT_MAX_TOPIC_LENGTH   80"

.SS "#define _GN_MQTT_PAYLOAD_OTA   'OTA'"

.SS "#define _GN_MQTT_PAYLOAD_RBT   'RBT'"

.SS "#define _GN_MQTT_PAYLOAD_RST   'RST'"

.SS "#define _GN_MQTT_STATUS_MESS   'sts'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_err_t\fP gn_mqtt_init (\fBgn_config_handle_t\fP config)"

.PP
inits the MQTT subsystem 
.PP
\fBParameters\fP
.RS 4
\fIconfig\fP the configuration to use
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_ERR_INVALID_ARG in case of null _conf 
.PP
GN_RET_ERR_MQTT_ERROR in case of MQTT errors 
.PP
GN_RET_ERR in case of general errors 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_publish_leaf (\fBgn_leaf_handle_t\fP _leaf_config)"

.PP
subscribe leaf to the MQTT server in order to receive messages 
.PP
\fBParameters\fP
.RS 4
\fIleaf_config\fP the leaf to start
.RE
.PP
\fBReturns\fP
.RS 4
status of the operation 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_leaf_message (\fBgn_leaf_handle_t\fP _leaf, const char * msg)"
@sends a command message to the specific leaf
.PP
\fBParameters\fP
.RS 4
\fI_leaf\fP the recipient leaf 
.br
\fImsg\fP payload
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_OK if successful 
.PP
GN_RET_ERR_INVALID_ARG if _config is null 
.PP
GN_RET_ERR_MQTT_ERROR if not possible to send message 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_leaf_param (\fBgn_leaf_param_handle_t\fP config)"

.SS "\fBgn_err_t\fP gn_mqtt_send_log_message (\fBgn_config_handle_t\fP _config, char * log_tag, \fBgn_log_level_t\fP level, char * message)"

.PP
sends log message via MQTT this uses the log level of the tag in understanding if the message has to be sent, in a similar way to ESP_LOGX
.PP
\fBParameters\fP
.RS 4
\fI_config\fP the configuration to use 
.br
\fIlog_tag\fP the tag to be checked against 
.br
\fIlevel\fP the log level to be checked 
.br
\fImessage\fP the payload
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_OK in case of successful sent 
.PP
GN_RET_ERR general error 
.PP
GN_RET_MQTT_ERROR on server error 
.PP
GN_RET_ERR_INVALID_ARG in case of arguments null 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_node_config (\fBgn_node_handle_t\fP _node_config)"

.PP
send node parameters via JSON message to the server this sends only if the node has already been started (status = GN_CONFIG_STATUS_STARTED)
.PP
\fBParameters\fP
.RS 4
\fI_node_config\fP the node to publish
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_ERR_INVALID_ARG if node config is null 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_ota_message (\fBgn_config_handle_t\fP _config)"
@sends a JSON message saying the board is going to download the firmware
.PP
payload is {'msgtype':'OTA'}
.PP
\fBParameters\fP
.RS 4
\fI_config\fP the configuration to use
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_OK if successful 
.PP
GN_RET_ERR_INVALID_ARG if _config is null 
.PP
GN_RET_ERR_MQTT_ERROR if not possible to send message 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_reboot_message (\fBgn_config_handle_t\fP _config)"
@sends a JSON message saying the board is rebooted
.PP
payload is {'msgtype':'RBT'}
.PP
\fBParameters\fP
.RS 4
\fI_config\fP the configuration to use
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_OK if successful 
.PP
GN_RET_ERR_INVALID_ARG if _config is null 
.PP
GN_RET_ERR_MQTT_ERROR if not possible to send message 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_reset_message (\fBgn_config_handle_t\fP _config)"
@sends a JSON message saying the board is going to reset
.PP
payload is {'msgtype':'RST'}
.PP
\fBParameters\fP
.RS 4
\fI_config\fP the configuration to use
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_OK if successful 
.PP
GN_RET_ERR_INVALID_ARG if _config is null 
.PP
GN_RET_ERR_MQTT_ERROR if not possible to send message 
.RE
.PP

.SS "\fBgn_err_t\fP gn_mqtt_send_startup_message (\fBgn_config_handle_t\fP _config)"
@sends a JSON message saying the board is online
.PP
payload is {'msgtype':'online'}
.PP
\fBParameters\fP
.RS 4
\fI_config\fP the configuration to use
.RE
.PP
\fBReturns\fP
.RS 4
GN_RET_OK if successful 
.PP
GN_RET_ERR_INVALID_ARG if _config is null 
.PP
GN_RET_ERR_MQTT_ERROR if not possible to send message 
.RE
.PP

.SS "esp_err_t gn_mqtt_subscribe_leaf_param (\fBgn_leaf_param_handle_t\fP param)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
