.TH "gn_node_event_t" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_node_event_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_event_id_t\fP \fBid\fP"
.br
.ti -1c
.RI "char \fBnode_name\fP [\fBGN_NODE_NAME_SIZE\fP]"
.br
.ti -1c
.RI "void * \fBdata\fP [\fBGN_NODE_DATA_SIZE\fP]"
.br
.ti -1c
.RI "int \fBdata_size\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void* gn_node_event_t::data[\fBGN_NODE_DATA_SIZE\fP]"
Data associated with this event 
.SS "int gn_node_event_t::data_size"
Length of the data for this event 
.SS "\fBgn_event_id_t\fP gn_node_event_t::id"

.SS "char gn_node_event_t::node_name[\fBGN_NODE_NAME_SIZE\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
