.TH "gn_node_config_t" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_node_config_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [\fBGN_NODE_NAME_SIZE\fP]"
.br
.ti -1c
.RI "\fBgn_config_handle_intl_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBgn_leaves_list\fP \fBleaves\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_config_handle_intl_t\fP gn_node_config_t::config"

.SS "\fBgn_leaves_list\fP gn_node_config_t::leaves"

.SS "char gn_node_config_t::name[\fBGN_NODE_NAME_SIZE\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
