.TH "components/grownode/gn_network.h" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/gn_network.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fB_gn_init_wifi\fP (\fBgn_config_handle_t\fP conf)"
.br
.ti -1c
.RI "void \fB_gn_ota_task\fP (void *pvParameter)"
.br
.ti -1c
.RI "esp_err_t \fB_gn_init_time_sync\fP (\fBgn_config_handle_t\fP conf)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "esp_err_t _gn_init_time_sync (\fBgn_config_handle_t\fP conf)"

.SS "esp_err_t _gn_init_wifi (\fBgn_config_handle_t\fP conf)"

.SS "void _gn_ota_task (void * pvParameter)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
