.TH "components/grownode/leaves/gn_pwm.h" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_pwm.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_leaf_pwm_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBGN_LEAF_PWM_TYPE\fP [] = 'pwm'"
.br
.ti -1c
.RI "static const char \fBGN_LEAF_PWM_PARAM_TOGGLE\fP [] = 'toggle'"
.br
.ti -1c
.RI "static const char \fBGN_LEAF_PWM_PARAM_POWER\fP [] = 'power'"
.br
.ti -1c
.RI "static const char \fBGN_LEAF_PWM_PARAM_CHANNEL\fP [] = 'channel'"
.br
.ti -1c
.RI "static const char \fBGN_LEAF_PWM_PARAM_GPIO\fP [] = 'gpio'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_leaf_pwm_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const char GN_LEAF_PWM_PARAM_CHANNEL[] = 'channel'\fC [static]\fP"
0-7 
.SS "const char GN_LEAF_PWM_PARAM_GPIO[] = 'gpio'\fC [static]\fP"
the GPIO to connect the pump (must be PWM capable) 
.SS "const char GN_LEAF_PWM_PARAM_POWER[] = 'power'\fC [static]\fP"
0 = off, 1024 = maximum 
.SS "const char GN_LEAF_PWM_PARAM_TOGGLE[] = 'toggle'\fC [static]\fP"
0 = off, 1 = on 
.SS "const char GN_LEAF_PWM_TYPE[] = 'pwm'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
