.TH "components/grownode/leaves/gn_pump.c" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_pump.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_pump_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_pump'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_pump_task\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_pump_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TAG   'gn_leaf_pump'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_pump_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SS "void gn_pump_task (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
