.TH "components/grownode/leaves/gn_pump_hs.c" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_pump_hs.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_pump_hs_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_pump_hs'"
.br
.ti -1c
.RI "#define \fBGN_LEAF_PWM_FADE_SPEED\fP   500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static bool \fBcb_ledc_fade_end_event\fP (const ledc_cb_param_t *param, void *user_arg)"
.br
.ti -1c
.RI "void \fBgn_leaf_pwm_task\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_pump_hs_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const ledc_mode_t \fBGN_PUMP_HS_PARAM_LEDC_MODE\fP = LEDC_LOW_SPEED_MODE"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GN_LEAF_PWM_FADE_SPEED   500"
define fade speed (msec) 
.SS "#define TAG   'gn_leaf_pump_hs'"

.SH "Function Documentation"
.PP 
.SS "static bool cb_ledc_fade_end_event (const ledc_cb_param_t * param, void * user_arg)\fC [static]\fP"

.SS "void gn_leaf_pwm_task (\fBgn_leaf_handle_t\fP leaf_config)"

.SS "\fBgn_leaf_descriptor_handle_t\fP gn_pump_hs_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Variable Documentation"
.PP 
.SS "const ledc_mode_t GN_PUMP_HS_PARAM_LEDC_MODE = LEDC_LOW_SPEED_MODE\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
