.TH "components/grownode/leaves/gn_pump_control.c" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_pump_control.c
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_pump_control'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_pump_control_task\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "void \fBgn_pump_control_task_event_handler\fP (void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_pump_control_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "size_t \fBpump_status\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TAG   'gn_leaf_pump_control'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_pump_control_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_pump_control_task (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_pump_control_task_event_handler (void * handler_args, esp_event_base_t base, int32_t event_id, void * event_data)"

.SH "Variable Documentation"
.PP 
.SS "size_t pump_status = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
