.TH "components/grownode/leaves/gn_pwm.c" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_pwm.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_pump_hs_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_pwm'"
.br
.ti -1c
.RI "#define \fBGN_PUMP_HS_FADE\fP"
.br
.ti -1c
.RI "#define \fBGN_LEAF_PWM_FADE_SPEED\fP   500"
.br
.ti -1c
.RI "#define \fBGN_LEAF_PWM_UNKNOWN_CHANNEL\fP   \-1"
.br
.ti -1c
.RI "#define \fBGN_LEAF_PWM_UNKNOWN_POWER\fP   \-1"
.br
.ti -1c
.RI "#define \fBGN_LEAF_PWM_UNKNOWN_GPIO\fP   \-1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_leaf_pwm_task\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_leaf_pwm_config\fP (\fBgn_leaf_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GN_LEAF_PWM_FADE_SPEED   500"
define fade speed (msec) 
.SS "#define GN_LEAF_PWM_UNKNOWN_CHANNEL   \-1"

.SS "#define GN_LEAF_PWM_UNKNOWN_GPIO   \-1"

.SS "#define GN_LEAF_PWM_UNKNOWN_POWER   \-1"

.SS "#define GN_PUMP_HS_FADE"
define if duty has to be faded 
.SS "#define TAG   'gn_leaf_pwm'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_leaf_pwm_config (\fBgn_leaf_handle_t\fP leaf_config)"

.SS "void gn_leaf_pwm_task (\fBgn_leaf_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
