.TH "gn_pump_data_t" 3 "Sat Jan 29 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_pump_data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_pump_channel_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_pump_toggle_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_pump_gpio_toggle_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_pump_power_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_pump_gpio_power_param\fP"
.br
.ti -1c
.RI "mcpwm_unit_t \fBpwm_unit\fP"
.br
.ti -1c
.RI "mcpwm_timer_t \fBpwm_timer\fP"
.br
.ti -1c
.RI "mcpwm_generator_t \fBpwm_generator\fP"
.br
.ti -1c
.RI "mcpwm_pin_config_t * \fBpin_config\fP"
.br
.ti -1c
.RI "mcpwm_config_t * \fBpwm_config\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_param_handle_t\fP gn_pump_data_t::gn_pump_channel_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_pump_data_t::gn_pump_gpio_power_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_pump_data_t::gn_pump_gpio_toggle_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_pump_data_t::gn_pump_power_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_pump_data_t::gn_pump_toggle_param"

.SS "mcpwm_pin_config_t* gn_pump_data_t::pin_config"

.SS "mcpwm_config_t* gn_pump_data_t::pwm_config"

.SS "mcpwm_generator_t gn_pump_data_t::pwm_generator"

.SS "mcpwm_timer_t gn_pump_data_t::pwm_timer"

.SS "mcpwm_unit_t gn_pump_data_t::pwm_unit"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
