.TH "gn_relay_data_t" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_relay_data_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_relay_status_param\fP"
.br
.ti -1c
.RI "\fBgn_leaf_param_handle_t\fP \fBgn_relay_gpio_param\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBgn_leaf_param_handle_t\fP gn_relay_data_t::gn_relay_gpio_param"

.SS "\fBgn_leaf_param_handle_t\fP gn_relay_data_t::gn_relay_status_param"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
