.TH "components/grownode/leaves/gn_relay.c" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_relay.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_relay_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOG_LOCAL_LEVEL\fP   ESP_LOG_VERBOSE"
.br
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_relay'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_relay_task\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_relay_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOG_LOCAL_LEVEL   ESP_LOG_VERBOSE"

.SS "#define TAG   'gn_leaf_relay'"

.SH "Function Documentation"
.PP 
.SS "\fBgn_leaf_descriptor_handle_t\fP gn_relay_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_relay_task (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
