.TH "gn_val_t" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gn_val_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "bool \fBb\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool gn_val_t::b"

.SS "double gn_val_t::d"

.SS "char* gn_val_t::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
