.TH "components/grownode/leaves/gn_watering_control.c" 3 "Wed Dec 8 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/leaves/gn_watering_control.c
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgn_watering_control_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTAG\fP   'gn_leaf_watering_control'"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBgn_hcc_status\fP { \fBHCC_HEATING\fP, \fBHCC_COOLING\fP, \fBHCC_OFF\fP }"
.br
.ti -1c
.RI "enum \fBgn_wat_status\fP { \fBWAT_WAIT\fP, \fBWAT_ON\fP, \fBWAT_OFF\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgn_watering_control_task\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_param_validator_result_t\fP \fB_gn_watering_interval_validator\fP (\fBgn_leaf_param_handle_t\fP param, void **param_value)"
.br
.ti -1c
.RI "\fBgn_leaf_param_validator_result_t\fP \fB_gn_watering_time_validator\fP (\fBgn_leaf_param_handle_t\fP param, void **param_value)"
.br
.ti -1c
.RI "\fBgn_leaf_param_validator_result_t\fP \fB_gn_watering_target_temp_validator\fP (\fBgn_leaf_param_handle_t\fP param, void **param_value)"
.br
.ti -1c
.RI "void \fB_gn_watering_callback_intl\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.ti -1c
.RI "\fBgn_leaf_descriptor_handle_t\fP \fBgn_watering_control_config\fP (\fBgn_leaf_config_handle_t\fP leaf_config)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TAG   'gn_leaf_watering_control'"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBgn_hcc_status\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHCC_HEATING \fP\fP
.TP
\fB\fIHCC_COOLING \fP\fP
.TP
\fB\fIHCC_OFF \fP\fP
.SS "enum \fBgn_wat_status\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWAT_WAIT \fP\fP
.TP
\fB\fIWAT_ON \fP\fP
.TP
\fB\fIWAT_OFF \fP\fP
.SH "Function Documentation"
.PP 
.SS "void _gn_watering_callback_intl (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "\fBgn_leaf_param_validator_result_t\fP _gn_watering_interval_validator (\fBgn_leaf_param_handle_t\fP param, void ** param_value)"

.SS "\fBgn_leaf_param_validator_result_t\fP _gn_watering_target_temp_validator (\fBgn_leaf_param_handle_t\fP param, void ** param_value)"

.SS "\fBgn_leaf_param_validator_result_t\fP _gn_watering_time_validator (\fBgn_leaf_param_handle_t\fP param, void ** param_value)"

.SS "\fBgn_leaf_descriptor_handle_t\fP gn_watering_control_config (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SS "void gn_watering_control_task (\fBgn_leaf_config_handle_t\fP leaf_config)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
