.TH "table_entry_s" 3 "Thu Dec 30 2021" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table_entry_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBhash\fP"
.br
.ti -1c
.RI "struct \fBtable_entry_s\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A CC_HashTable table entry\&.
.PP
\fBNote\fP
.RS 4
modifying this structure may invalidate the table\&. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "size_t table_entry_s::hash"
Hash of the key 
.SS "void* table_entry_s::key"
A key in the table 
.SS "struct \fBtable_entry_s\fP* table_entry_s::next"
Pointer the next entry in the list\&. 
.SS "void* table_entry_s::value"
Value associated with the key 

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
