.TH "components/grownode/test/test_bme280.c" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/test/test_bme280.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_gn_mqtt_event_handler\fP (void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data)"
.br
.ti -1c
.RI "void \fB_gn_mqtt_build_leaf_parameter_command_topic\fP (const \fBgn_leaf_handle_t\fP _leaf_config, const char *param_name, char *buf)"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_init_add_bme280', '[bme280]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_leaf_create bme280', '[bme280]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_bme280_mqtt_stress_test', '[bme280]')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgn_config_handle_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBgn_node_handle_t\fP \fBnode_config\fP"
.br
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBbme280_config\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _gn_mqtt_build_leaf_parameter_command_topic (const \fBgn_leaf_handle_t\fP _leaf_config, const char * param_name, char * buf)"

.SS "void _gn_mqtt_event_handler (void * handler_args, esp_event_base_t base, int32_t event_id, void * event_data)"

.SS "TEST_CASE ('gn_bme280_mqtt_stress_test', ''[bme280])"

.SS "TEST_CASE ('gn_init_add_bme280', ''[bme280])"

.SS "TEST_CASE ('gn_leaf_create bme280', ''[bme280])"

.SH "Variable Documentation"
.PP 
.SS "\fBgn_leaf_handle_t\fP bme280_config"

.SS "\fBgn_config_handle_t\fP config\fC [extern]\fP"

.SS "\fBgn_node_handle_t\fP node_config\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
