.TH "components/grownode/test/test_grownode.c" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/test/test_grownode.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_init', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_firmware_update', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_reset', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_reboot', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_node_create', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_start', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_loop_1s', '[gn_system]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_set_blob_string', '[gn_storage]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_get_blob_string', '[gn_storage]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_set_blob_double', '[gn_storage]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_get_blob_double', '[gn_storage]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_test_log', '[gn_display]')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgn_config_handle_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBgn_node_handle_t\fP \fBnode_config\fP"
.br
.ti -1c
.RI "\fBgn_config_init_param_t\fP \fBconfig_init\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void setUp ()"

.SS "void tearDown ()"

.SS "TEST_CASE ('gn_firmware_update', ''[gn_system])"

.SS "TEST_CASE ('gn_get_blob_double', ''[gn_storage])"

.SS "TEST_CASE ('gn_get_blob_string', ''[gn_storage])"

.SS "TEST_CASE ('gn_init', ''[gn_system])"

.SS "TEST_CASE ('gn_loop_1s', ''[gn_system])"

.SS "TEST_CASE ('gn_node_create', ''[gn_system])"

.SS "TEST_CASE ('gn_reboot', ''[gn_system])"

.SS "TEST_CASE ('gn_reset', ''[gn_system])"

.SS "TEST_CASE ('gn_set_blob_double', ''[gn_storage])"

.SS "TEST_CASE ('gn_set_blob_string', ''[gn_storage])"

.SS "TEST_CASE ('gn_start', ''[gn_system])"

.SS "TEST_CASE ('gn_test_log', ''[gn_display])"

.SH "Variable Documentation"
.PP 
.SS "\fBgn_config_handle_t\fP config"

.SS "\fBgn_config_init_param_t\fP config_init"
\fBInitial value:\fP
.PP
.nf
= { \&.provisioning_security = true,
        \&.provisioning_password = "grownode", \&.server_board_id_topic = false,
        \&.server_base_topic = "server_base_topic", \&.server_url = "server_url",
        \&.server_keepalive_timer_sec = 60, \&.server_discovery = false,
        \&.firmware_url = "firmware_url", \&.sntp_url = "sntp_url" }
.fi
.SS "\fBgn_node_handle_t\fP node_config"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
