.TH "components/grownode/test/test_relay.c" 3 "Fri Jan 28 2022" "GrowNode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/grownode/test/test_relay.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_gn_mqtt_event_handler\fP (void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data)"
.br
.ti -1c
.RI "void \fB_gn_mqtt_build_leaf_parameter_command_topic\fP (const \fBgn_leaf_handle_t\fP _leaf_config, const char *param_name, char *buf)"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_init_add_relay', '[relay]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_leaf_create relay', '[relay]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_receive_status_0', '[relay]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_receive_status_1', '[relay]')"
.br
.ti -1c
.RI "\fBTEST_CASE\fP ('gn_relay_mqtt_stress_test', '[relay]')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgn_config_init_param_t\fP \fBconfig_init\fP"
.br
.ti -1c
.RI "\fBgn_config_handle_t\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBgn_node_handle_t\fP \fBnode_config\fP"
.br
.ti -1c
.RI "\fBgn_leaf_handle_t\fP \fBrelay_config\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _gn_mqtt_build_leaf_parameter_command_topic (const \fBgn_leaf_handle_t\fP _leaf_config, const char * param_name, char * buf)"

.SS "void _gn_mqtt_event_handler (void * handler_args, esp_event_base_t base, int32_t event_id, void * event_data)"

.SS "TEST_CASE ('gn_init_add_relay', ''[relay])"

.SS "TEST_CASE ('gn_leaf_create relay', ''[relay])"

.SS "TEST_CASE ('gn_receive_status_0', ''[relay])"

.SS "TEST_CASE ('gn_receive_status_1', ''[relay])"

.SS "TEST_CASE ('gn_relay_mqtt_stress_test', ''[relay])"

.SH "Variable Documentation"
.PP 
.SS "\fBgn_config_handle_t\fP config\fC [extern]\fP"

.SS "\fBgn_config_init_param_t\fP config_init"
\fBInitial value:\fP
.PP
.nf
= {
    \&.provisioning_security = true,
    \&.provisioning_password = "grownode",
    \&.server_board_id_topic = false,
    \&.server_base_topic = "server_base_topic",
    \&.server_url = "server_url",
    \&.server_keepalive_timer_sec = 60,
    \&.server_discovery = false,
    \&.firmware_url = "firmware_url",
    \&.sntp_url = "sntp_url"
}
.fi
.SS "\fBgn_node_handle_t\fP node_config\fC [extern]\fP"

.SS "\fBgn_leaf_handle_t\fP relay_config"

.SH "Author"
.PP 
Generated automatically by Doxygen for GrowNode from the source code\&.
